import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {ActivityIndicator,RefreshControl,ScrollView,StyleSheet,Text,TouchableOpacity,View} from 'react-native';
import {useRouter} from 'expo-router'; import {ArrowLeft,CalendarCheck,IndianRupee,Repeat2,UserX,TrendingUp} from 'lucide-react-native';
import {collection,getDocs,limit,query,where} from 'firebase/firestore'; import {db} from '@/config/firebase'; import {useAuth} from '@/context/auth'; import Colors from '@/constants/Colors'; import {useSafeAreaInsets} from 'react-native-safe-area-context';
const chunks=<T,>(a:T[],n=30)=>Array.from({length:Math.ceil(a.length/n)},(_,i)=>a.slice(i*n,i*n+n));
export default function OwnerAnalytics(){const {user}=useAuth();const router=useRouter();const insets=useSafeAreaInsets();const [rows,setRows]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);
const load=useCallback(async()=>{if(!user?.uid)return;try{const ss=await getDocs(query(collection(db,'shops'),where('ownerId','==',user.uid),limit(30)));const ids=ss.docs.map(x=>x.id);const out:any[]=[];for(const c of ['appointments','familybookings'])for(const part of chunks(ids)){if(!part.length)continue;const s=await getDocs(query(collection(db,c),where('shopId','in',part),limit(500)));s.forEach(x=>out.push(x.data()))}setRows(out)}finally{setLoading(false);setRefreshing(false)}},[user?.uid]);useEffect(()=>{load()},[load]);
const m=useMemo(()=>{const valid=rows.filter(x=>x.status!=='cancelled');const completed=valid.filter(x=>x.status==='completed');const revenue=completed.reduce((s,x)=>s+Number(x.totalAmount||x.amount||x.price||0),0);const users=new Set(valid.map(x=>x.userId).filter(Boolean));const counts=new Map<string,number>();valid.forEach(x=>x.userId&&counts.set(x.userId,(counts.get(x.userId)||0)+1));const repeat=[...counts.values()].filter(x=>x>1).length;const noShows=rows.filter(x=>x.status==='no-show'||x.status==='noshow').length;const byDay=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(6-i));const key=d.toISOString().slice(0,10);return {label:d.toLocaleDateString('en-IN',{weekday:'short'}),count:valid.filter(x=>String(x.dateTime||'').slice(0,10)===key).length}});return{bookings:valid.length,revenue,customers:users.size,repeat,noShows,byDay,max:Math.max(1,...byDay.map(x=>x.count))}},[rows]);
return <View style={s.page}><View style={[s.header,{paddingTop:insets.top+12}]}><TouchableOpacity onPress={()=>router.back()} style={s.back}><ArrowLeft size={22} color={Colors.text}/></TouchableOpacity><View><Text style={s.title}>Business Analytics</Text><Text style={s.sub}>Fast operational view of your salons</Text></View></View><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);load()}}/>} contentContainerStyle={s.content}>{loading?<ActivityIndicator size="large" color={Colors.primary} style={{marginTop:50}}/>:<><View style={s.grid}><K icon={<CalendarCheck size={21} color={Colors.primary}/>} l="Bookings" v={`${m.bookings}`}/><K icon={<IndianRupee size={21} color={Colors.primary}/>} l="Completed revenue" v={`₹${Math.round(m.revenue).toLocaleString('en-IN')}`}/><K icon={<Repeat2 size={21} color={Colors.primary}/>} l="Repeat customers" v={`${m.repeat}`}/><K icon={<UserX size={21} color={Colors.primary}/>} l="No-shows" v={`${m.noShows}`}/></View><View style={s.panel}><View style={s.panelHead}><Text style={s.panelTitle}>Last 7 days</Text><TrendingUp size={20} color={Colors.primary}/></View><View style={s.chart}>{m.byDay.map((d:any)=><View key={d.label} style={s.barCol}><Text style={s.barValue}>{d.count}</Text><View style={[s.bar,{height:Math.max(8,(d.count/m.max)*120)}]}/><Text style={s.barLabel}>{d.label}</Text></View>)}</View></View><View style={s.panel}><Text style={s.panelTitle}>Retention snapshot</Text><Text style={s.big}>{m.customers?Math.round((m.repeat/m.customers)*100):0}%</Text><Text style={s.explain}>of known customers booked more than once. Use Customer CRM to follow up with lapsed customers.</Text></View></>}</ScrollView></View>}
function K({icon,l,v}:{icon:React.ReactNode;l:string;v:string}){return <View style={s.kpi}>{icon}<Text style={s.kpiV} numberOfLines={1}>{v}</Text><Text style={s.kpiL}>{l}</Text></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:Colors.background},header:{paddingHorizontal:20,paddingBottom:16,flexDirection:'row',alignItems:'center',borderBottomWidth:1,borderBottomColor:Colors.border},back:{width:40,height:40,borderRadius:20,alignItems:'center',justifyContent:'center',marginRight:10},title:{fontFamily:'Poppins-Bold',fontSize:24,color:Colors.text},sub:{fontFamily:'Poppins-Regular',fontSize:13,color:Colors.textLight},content:{padding:16,paddingBottom:40},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},kpi:{width:'48%',backgroundColor:Colors.cardBackground,borderWidth:1,borderColor:Colors.border,borderRadius:14,padding:14},kpiV:{fontFamily:'Poppins-Bold',fontSize:21,color:Colors.text,marginTop:10},kpiL:{fontFamily:'Poppins-Regular',fontSize:12,color:Colors.textLight},panel:{marginTop:16,backgroundColor:Colors.cardBackground,borderWidth:1,borderColor:Colors.border,borderRadius:16,padding:16},panelHead:{flexDirection:'row',justifyContent:'space-between'},panelTitle:{fontFamily:'Poppins-SemiBold',fontSize:16,color:Colors.text},chart:{height:175,flexDirection:'row',alignItems:'flex-end',justifyContent:'space-around',marginTop:12},barCol:{height:160,flex:1,alignItems:'center',justifyContent:'flex-end'},bar:{width:20,borderRadius:8,backgroundColor:Colors.primary,marginVertical:6},barValue:{fontFamily:'Poppins-Medium',fontSize:11,color:Colors.text},barLabel:{fontFamily:'Poppins-Regular',fontSize:10,color:Colors.textLight},big:{fontFamily:'Poppins-Bold',fontSize:42,color:Colors.primary,marginTop:12},explain:{fontFamily:'Poppins-Regular',fontSize:13,lineHeight:20,color:Colors.textLight}});
