import React,{useState} from 'react';
import {Alert,Platform,ScrollView,Share,StyleSheet,Text,TouchableOpacity,View} from 'react-native';
import {collection,getDocs,limit,query} from 'firebase/firestore';
import {db} from '@/config/firebase';
import Colors from '@/constants/Colors';
import {useRouter} from 'expo-router';
import {ArrowLeft,Download} from 'lucide-react-native';
const sets=['appointments','familybookings','barberowner','shops','users','services','packages','offers','reviews','staff'];
const esc=(v:any)=>`"${String(v??'').replace(/"/g,'""')}"`;
export default function AdminReports(){const r=useRouter();const [busy,setBusy]=useState('');const run=async(name:string)=>{try{setBusy(name);const s=await getDocs(query(collection(db,name),limit(2000)));const rows=s.docs.map(d=>({id:d.id,...(d.data() as any)}));if(!rows.length){Alert.alert('No data',`No ${name} records are available.`);return}const keys=Array.from(new Set(rows.flatMap(x=>Object.keys(x))));const csv=[keys.map(esc).join(','),...rows.map(x=>keys.map(k=>esc(typeof x[k]==='object'?JSON.stringify(x[k]):x[k])).join(','))].join('\n');if(Platform.OS==='web'){const blob=new Blob([csv],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`mybarber_${name}.csv`;a.click();URL.revokeObjectURL(url)}else await Share.share({title:`MyBarber ${name} report`,message:csv})}catch(e:any){Alert.alert('Export failed',e?.message||'Please try again.')}finally{setBusy('')}};return <View style={s.page}><View style={s.head}><TouchableOpacity onPress={()=>r.back()}><ArrowLeft size={22} color={Colors.text}/></TouchableOpacity><View><Text style={s.title}>Reports & Exports</Text><Text style={s.sub}>Download operational data as CSV</Text></View></View><ScrollView contentContainerStyle={s.list}>{sets.map(x=><TouchableOpacity key={x} style={s.card} onPress={()=>run(x)} disabled={!!busy}><View><Text style={s.name}>{x.replace(/_/g,' ')}</Text><Text style={s.meta}>Up to 2,000 latest records</Text></View><View style={s.icon}><Download size={18} color={Colors.primary}/><Text style={s.action}>{busy===x?'Preparing…':'Export'}</Text></View></TouchableOpacity>)}</ScrollView></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:Colors.background,paddingTop:Platform.OS==='ios'?54:34},head:{padding:18,flexDirection:'row',alignItems:'center',gap:14},title:{fontFamily:'Poppins-Bold',fontSize:23,color:Colors.text},sub:{fontFamily:'Poppins-Regular',fontSize:12,color:Colors.textLight},list:{padding:18,gap:12},card:{backgroundColor:'#fff',padding:16,borderRadius:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderWidth:1,borderColor:Colors.border},name:{fontFamily:'Poppins-SemiBold',fontSize:15,color:Colors.text,textTransform:'capitalize'},meta:{fontFamily:'Poppins-Regular',fontSize:11,color:Colors.textLight},icon:{flexDirection:'row',alignItems:'center',gap:6},action:{fontFamily:'Poppins-SemiBold',fontSize:12,color:Colors.primary}});
